

#define crypto_aead_encrypt_tiny_asm encrypt_tiny_asm
#define crypto_aead_encrypt_tiny_asm_new_api encrypt_tiny_asm_new_api
#define crypto_aead_encrypt_tiny encrypt_tiny
#define tiny_permutation_asm tiny_rv32
#define tiny_permutation_C state_update